import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image
import json
import os

# ========================================================
# PAGE CONFIGURATION
# ========================================================

st.set_page_config(
    page_title="Lung CancerAI | Pulmonary CT/X-Ray Analysis",
    page_icon="🫁",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ========================================================
# GLOBAL PATHS & SETTINGS
# ========================================================

MODEL_PATH = "models/lung_cancer_cnn.keras"

METRICS_PATH = "results/metrics.json"

CONFUSION_MATRIX_PATH = (
    "results/confusion_matrix.png"
)

ROC_CURVE_PATH = (
    "results/roc_curve.png"
)

# Must match the training script shape
IMG_SIZE = (256, 256)

# ========================================================
# CUSTOM CSS INJECTION
# ========================================================

st.markdown(
    """
    <style>
    .main-title {
        font-size: 40px;
        font-weight: bold;
    }

    .subtitle {
        font-size: 20px;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# ========================================================
# MODEL CACHING & LOADING
# ========================================================

@st.cache_resource
def load_lung_model():
    """
    Loads the compiled Keras model securely
    and caches it in memory.
    """

    try:
        return tf.keras.models.load_model(
            MODEL_PATH
        )

    except Exception as e:
        st.error(
            "CRITICAL ERROR: Unable to load "
            "the trained Deep CNN model."
        )

        st.exception(e)
        st.stop()


model = load_lung_model()

# ========================================================
# SIDEBAR NAVIGATION & INFO
# ========================================================

with st.sidebar:

    st.markdown(
        "### Lung CancerAI"
    )

    st.markdown(
        "Advanced Pulmonary Intelligence"
    )

    st.divider()

    st.markdown(
        "### System Architecture"
    )

    st.write(
        "Deep Convolutional Neural Network Classification"
    )

    st.write(
        "**Modality Input:** Chest CT / X-ray"
    )

    st.write(
        "**Prediction Output:** Benign / Malignant"
    )

    st.divider()

    st.markdown(
        "### Model Specification"
    )

    st.write(
        f"**Image Input Shape:** "
        f"{IMG_SIZE[0]} x {IMG_SIZE[1]} x 3"
    )

    st.write(
        "**Classes Detected:** 2 (Binary)"
    )

    st.write(
        "**Activation:** Sigmoid"
    )

    st.divider()

    st.markdown(
        "### Privacy Protocol"
    )

    st.write(
        "All radiological images uploaded remain "
        "in volatile memory and are purged after "
        "the session ends."
    )

# ========================================================
# MAIN DASHBOARD HEADER
# ========================================================

st.markdown(
    '<div class="main-title">'
    'LungCancerAI Portal'
    '</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">'
    'State-of-the-art Deep Learning inference '
    'for automated lung nodule and mass characterization.'
    '</div>',
    unsafe_allow_html=True
)

# ========================================================
# CLINICAL DISCLAIMER
# ========================================================

st.warning(
    "**CLINICAL DISCLAIMER:** This artificial "
    "intelligence diagnostic tool is designed for "
    "research and informational screening purposes only. "
    "It is not an FDA-approved medical device. "
    "Results generated by Lung CancerAI must be verified "
    "by a board-certified radiologist or oncologist."
)

# ========================================================
# IMAGE UPLOAD INTERFACE
# ========================================================

st.header(
    "Upload Radiological Scan"
)

st.write(
    "Please upload a high-resolution Chest CT "
    "slice or X-ray for AI examination."
)

uploaded_file = st.file_uploader(
    "Select Image Data",
    type=[
        "jpg",
        "jpeg",
        "png"
    ],
    help=(
        "Supported DICOM-converted formats: "
        "JPG, JPEG, and PNG. Max size: 20MB."
    )
)

# ========================================================
# INFERENCE PIPELINE
# ========================================================

if uploaded_file is not None:

    # Open image and force RGB conversion
    original_image = (
        Image.open(uploaded_file)
        .convert("RGB")
    )

    st.write("")

    col_img, col_analysis = st.columns(
        2,
        gap="large"
    )

    # ====================================================
    # COLUMN 1: DISPLAY UPLOADED IMAGE
    # ====================================================

    with col_img:

        with st.container(border=True):

            st.subheader(
                "Original Scan"
            )

            st.caption(
                "Patient radiological data "
                "pending analysis"
            )

            st.image(
                original_image,
                use_container_width=True
            )

    # ====================================================
    # COLUMN 2: ANALYSIS EXECUTION
    # ====================================================

    with col_analysis:

        with st.container(border=True):

            st.subheader(
                "Neural Network Analysis"
            )

            st.caption(
                "Execute feed-forward propagation "
                "through the CNN"
            )

            analyze_button = st.button(
                "Initialize Scan Analysis",
                use_container_width=True
            )

            if analyze_button:

                with st.spinner(
                    "Processing spatial features "
                    "and detecting anomalies..."
                ):

                    # 1. Resize image
                    resized_img = (
                        original_image.resize(
                            IMG_SIZE
                        )
                    )

                    # 2. Convert to NumPy array
                    img_array = np.array(
                        resized_img
                    )

                    # 3. Add batch dimension
                    # Shape: (1, 256, 256, 3)
                    img_array = np.expand_dims(
                        img_array,
                        axis=0
                    )

                    # Normalization is embedded
                    # inside the Keras model

                    # 4. Predict
                    probability = float(
                        model.predict(
                            img_array,
                            verbose=0
                        )[0][0]
                    )

                    # 5. Evaluate threshold
                    if probability >= 0.5:

                        prediction = (
                            "MALIGNANT "
                            "(LUNG CANCER)"
                        )

                        confidence = probability

                        st.error(
                            f"ALERT: {prediction}"
                        )

                        st.write(
                            "The deep learning model "
                            "detected visual biomarkers "
                            "heavily associated with "
                            "malignant lung tissue."
                        )

                    else:

                        prediction = (
                            "BENIGN (NORMAL)"
                        )

                        confidence = (
                            1.0 - probability
                        )

                        st.success(
                            f"SUCCESS: {prediction}"
                        )

                        st.write(
                            "The deep learning model "
                            "found no significant visual "
                            "biomarkers associated with "
                            "lung cancer."
                        )

                    # Display confidence
                    st.metric(
                        "Neural Network Confidence Score",
                        f"{confidence * 100:.2f}%"
                    )

                    st.progress(
                        confidence
                    )

# ========================================================
# PERFORMANCE METRICS SECTION
# ========================================================

st.divider()

st.header(
    "Model Validation Metrics"
)

st.write(
    "Quantitative assessment of the CNN model "
    "computed on the holdout test dataset."
)

if os.path.exists(METRICS_PATH):

    with open(
        METRICS_PATH,
        "r"
    ) as file:

        metrics = json.load(file)

    # First row
    m_col1, m_col2, m_col3 = st.columns(3)

    with m_col1:
        st.metric(
            "Global Accuracy",
            f"{metrics['accuracy'] * 100:.2f}%"
        )

    with m_col2:
        st.metric(
            "Precision (PPV)",
            f"{metrics['precision'] * 100:.2f}%"
        )

    with m_col3:
        st.metric(
            "Recall (Sensitivity)",
            f"{metrics['recall'] * 100:.2f}%"
        )

    st.write("")

    # Second row
    m_col4, m_col5, m_col6 = st.columns(3)

    with m_col4:
        st.metric(
            "F1 Harmonic Mean",
            f"{metrics['f1_score'] * 100:.2f}%"
        )

    with m_col5:
        st.metric(
            "Specificity (TNR)",
            f"{metrics['specificity'] * 100:.2f}%"
        )

    with m_col6:
        st.metric(
            "ROC-AUC Score",
            f"{metrics['roc_auc']:.4f}"
        )

else:

    st.warning(
        "Validation metrics JSON payload not found. "
        "Ensure evaluate.py has been executed."
    )

# ========================================================
# VISUAL EVALUATION PLOTS
# ========================================================

st.divider()

st.header(
    "Graphical Performance Evaluation"
)

st.write(
    "Visual representations of the classifier's "
    "diagnostic capability."
)

plot_col1, plot_col2 = st.columns(
    2,
    gap="large"
)

# ========================================================
# CONFUSION MATRIX
# ========================================================

with plot_col1:

    with st.container(border=True):

        st.subheader(
            "Confusion Matrix"
        )

        st.caption(
            "Distribution of True Positives, "
            "False Positives, True Negatives, "
            "and False Negatives."
        )

        if os.path.exists(
            CONFUSION_MATRIX_PATH
        ):

            st.image(
                CONFUSION_MATRIX_PATH,
                use_container_width=True
            )

        else:

            st.error(
                "Matrix visualization artifact missing."
            )

# ========================================================
# ROC CURVE
# ========================================================

with plot_col2:

    with st.container(border=True):

        st.subheader(
            "ROC Curve"
        )

        st.caption(
            "Trade-off between true positive rate "
            "and false positive rate across thresholds."
        )

        if os.path.exists(
            ROC_CURVE_PATH
        ):

            st.image(
                ROC_CURVE_PATH,
                use_container_width=True
            )

        else:

            st.error(
                "ROC visualization artifact missing."
            )

# ========================================================
# TECHNICAL DOCUMENTATION FOOTER
# ========================================================

st.divider()

st.header(
    "About the Diagnostic Engine"
)

info_col1, info_col2, info_col3 = st.columns(
    3,
    gap="large"
)

with info_col1:

    with st.container(border=True):

        st.subheader(
            "Deep CNN Topology"
        )

        st.write(
            "The model utilizes a custom hierarchical "
            "Convolutional Neural Network. It leverages "
            "spatial convolutions, batch normalization, "
            "and severe dropout regularization to isolate "
            "pulmonary nodules from healthy parenchymal tissue."
        )

with info_col2:

    with st.container(border=True):

        st.subheader(
            "Pre-Processing Logic"
        )

        st.write(
            "Incoming user images are dynamically scaled "
            "to 256x256 resolution. TensorFlow native layer "
            "rescaling normalizes pixel intensity distributions "
            "to a floating-point range of [0, 1] internally "
            "to ensure gradient stability."
        )

with info_col3:

    with st.container(border=True):

        st.subheader(
            "Decision Mechanics"
        )

        st.write(
            "The final dense layer outputs a continuous "
            "value through a Sigmoid activation. This float "
            "value represents the statistical likelihood of "
            "malignancy, binarized at a 0.5 boundary for "
            "clinical categorization."
        )

# ========================================================
# FOOTER
# ========================================================

st.markdown(
    "### Lung CancerAI Framework v1.0 | "
    "Precision Medical Image Analysis"
)
